In [24]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [28]:
X,y = make_classification(n_samples=1000,n_features=5,random_state=924)

In [29]:
X

array([[ 0.48693698,  0.71450093, -0.68006697, -1.60260971, -2.55358962],
       [ 0.99608132,  0.44528782, -0.13061133, -0.71858258, -0.98049254],
       [-1.45328025,  0.26920925,  0.79161352,  0.39745887,  1.2211465 ],
       ...,
       [-0.35812744,  1.04936458,  0.20545202, -1.20296562, -1.24122399],
       [ 1.13027083,  1.46579575,  0.8071397 , -1.1833085 , -0.65000172],
       [ 0.45920045, -0.93361761, -1.23296339,  0.06676583, -1.08381501]])

In [30]:
y

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=45)

In [32]:
X_train.shape

(700, 5)

In [33]:
X_test.shape

(300, 5)

In [34]:
model = LogisticRegression()

In [35]:
#you are training the model
model.fit(X_train,y_train)

LogisticRegression()

In [38]:
y_pred = model.predict(X_test)

In [39]:
accuracy_score(y_test,y_pred)

0.86

In [40]:
confusion_matrix(y_test,y_pred)

array([[121,  23],
       [ 19, 137]], dtype=int64)

In [41]:
model.score(X_train,y_train) #training accuarcy score

0.9028571428571428

In [42]:
0.9028571428571428 - 0.86

0.042857142857142816

In [ ]:
Overfitting:
    
    train accuracy is bvery good
    and test accuracy is not good

In [ ]:
lets 'say there is a medicval problem statement which we are sloving'
10,20,30,40 diff should be less train and test for model 

In [ ]:
underfitting:
     
    train accuracy and test accuracy both are not good

In [ ]:
Jupytet notebook

maintain proper commenting

Census Income
Energy efficiency

perform proper end to end EDA
Do FE and Preprocess
model craetion with logistic regressionand perform hyperparameter tuning
evaluate the model and print all the score and check with auc-roc as well
now give the conclusion which matix is corrwect according to problem statement